services:
  - type: static
    # name: camie-docs-mdx
    # env: node
    # buildCommand: npm ci && npm run build
    # publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
